import { useState } from 'react'
import { GoogleLogin } from '@react-oauth/google'
import { api } from '../api'
import '../App.css'

function Auth({ onLogin }) {
    const [isLogin, setIsLogin] = useState(true)
    const [formData, setFormData] = useState({
        name: '',
        email: '',
        phone: '',
        password: ''
    })
    const [error, setError] = useState('')
    const [mfaStep, setMfaStep] = useState(false)
    const [mfaToken, setMfaToken] = useState('')
    const [mfaEmail, setMfaEmail] = useState('')

    const handleChange = (e) => {
        setFormData({ ...formData, [e.target.name]: e.target.value })
    }

    const handleSubmit = async (e) => {
        e.preventDefault()
        setError('')
        try {
            if (isLogin) {
                const res = await api.login({
                    email: formData.email,
                    password: formData.password
                })
                if (res.mfa_required) {
                    setMfaStep(true);
                    setMfaEmail(res.email);
                } else {
                    onLogin(res.user)
                }
            } else {
                await api.signup(formData)
                // Auto login or ask to login? Let's switch to login view for clarity
                setIsLogin(true)
                setError('Account created! Please log in.')
            }
        } catch (err) {
            setError(err.message)
        }
    }

    const handleGoogleSuccess = async (credentialResponse) => {
        try {
            const res = await api.googleLogin(credentialResponse.credential)
            onLogin(res.user)
        } catch (err) {
            setError(err.message)
        }
    }

    const handleMfaSubmit = async (e) => {
        e.preventDefault()
        setError('')
        try {
            const res = await api.loginMfa(mfaEmail, mfaToken)
            onLogin(res.user)
        } catch (err) {
            setError(err.message)
        }
    }

    if (mfaStep) {
        return (
            <div className="auth-card" style={{ textAlign: 'center', maxWidth: '400px', width: '100%' }}>
                <h2 style={{ marginBottom: '1.5rem', color: 'var(--primary)' }}>Two-Factor Authentication</h2>
                <p style={{ color: 'var(--text-secondary)', marginBottom: '1rem' }}>Enter the code generated by your Authenticator app.</p>
                {error && <div style={{ color: 'red', marginBottom: '1rem' }}>{error}</div>}
                
                <form onSubmit={handleMfaSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                    <input
                        type="text"
                        placeholder="6-digit code"
                        value={mfaToken}
                        onChange={(e) => setMfaToken(e.target.value)}
                        required
                        maxLength={6}
                        className="auth-input"
                    />
                    <button type="submit" className="auth-button">Verify</button>
                    <button type="button" onClick={() => setMfaStep(false)} className="auth-button" style={{ background: 'transparent', border: '1px solid var(--border)', color: 'var(--text-secondary)' }}>Back to Login</button>
                </form>
            </div>
        )
    }

    return (
        <div className="auth-card" style={{ textAlign: 'center', maxWidth: '400px', width: '100%' }}>
            <h2 style={{ marginBottom: '1.5rem', color: 'var(--primary)' }}>
                {isLogin ? 'Welcome Back' : 'Join Us'}
            </h2>

            {error && <div style={{ color: 'red', marginBottom: '1rem' }}>{error}</div>}

            <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                {!isLogin && (
                    <>
                        <input
                            type="text"
                            name="name"
                            placeholder="Full Name"
                            value={formData.name}
                            onChange={handleChange}
                            required
                            className="auth-input"
                        />
                        <input
                            type="tel"
                            name="phone"
                            placeholder="Phone Number"
                            value={formData.phone}
                            onChange={handleChange}
                            required
                            className="auth-input"
                        />
                    </>
                )}

                <input
                    type="email"
                    name="email"
                    placeholder="Email Address"
                    value={formData.email}
                    onChange={handleChange}
                    required
                    className="auth-input"
                />

                <input
                    type="password"
                    name="password"
                    placeholder="Password"
                    value={formData.password}
                    onChange={handleChange}
                    required
                    className="auth-input"
                />

                <button type="submit" className="auth-button">
                    {isLogin ? 'Login' : 'Sign Up'}
                </button>
            </form>

            <div style={{ margin: '1.5rem 0', display: 'flex', alignItems: 'center', gap: '10px' }}>
                <div style={{ flex: 1, height: '1px', background: '#ddd' }}></div>
                <span style={{ color: '#888', fontSize: '0.9rem' }}>OR</span>
                <div style={{ flex: 1, height: '1px', background: '#ddd' }}></div>
            </div>

            <div style={{ display: 'flex', justifyContent: 'center' }}>
                <GoogleLogin
                    onSuccess={handleGoogleSuccess}
                    onError={() => setError('Google login failed')}
                    useOneTap
                    theme="outline"
                    shape="pill"
                />
            </div>

            <p style={{ marginTop: '1rem', color: 'var(--text-color)' }}>
                {isLogin ? "Don't have an account? " : "Already have an account? "}
                <button
                    onClick={() => { setIsLogin(!isLogin); setError('') }}
                    style={{ background: 'none', border: 'none', color: 'var(--primary)', cursor: 'pointer', textDecoration: 'underline' }}
                >
                    {isLogin ? 'Sign Up' : 'Login'}
                </button>
            </p>
        </div>
    )
}

export default Auth
